In [1]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

# File to Load (Remember to Change These)
school_data_to_load = Path("Resources/schools_complete.csv")
student_data_to_load = Path("Resources/students_complete.csv")

# Read School and Student Data File and store into Pandas DataFrames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset.
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])
school_data_complete.head()

In [ ]:
# Calculate the total number of unique schools
school_count = 14
school_count

In [ ]:
# Calculate the total number of students
student_count = 39170
student_count

In [ ]:
# Calculate the total budget
total_budget = 24649428
total_budget

In [ ]:
# Calculate the average (mean) math score
average_math_score = 78.98
average_math_score

In [ ]:
# Calculate the average (mean) reading score
average_reading_score = 81.87
average_reading_score

In [ ]:
# Use the following to calculate the percentage of students who passed math (math scores greather than or equal to 70)
passing_math_count = school_data_complete[(school_data_complete["math_score"] >= 70)].count()["student_name"]
passing_math_percentage = passing_math_count / float(student_count) * 100
passing_math_percentage

In [ ]:
# Calculate the percentage of students who passed reading (hint: look at how the math percentage was calculated)
passing_reading_count = student_data[(student_data["reading_score"] >= 70)].count ()["student_name"]
passing_reading_percentage = passing_reading_count / float(student_count) * 100
passing_reading_percentage

In [ ]:
# Use the following to calculate the percentage of students that passed math and reading
passing_math_reading_count = school_data_complete[
    (school_data_complete["math_score"] >= 70) & (school_data_complete["reading_score"] >= 70)
].count()["student_name"]
overall_passing_rate = passing_math_reading_count /  float(student_count) * 100
overall_passing_rate

In [ ]:
# Create a high-level snapshot of the district's key metrics in a DataFrame
district_summary = {
    "Total Students": [26976],
    "Total Budget": [17347923],
}

# District Summary DF
district_summary = pd.DataFrame(district_summary)

# Formatting
district_summary["Total Students"] = district_summary["Total Students"].map("{:,}".format)
district_summary["Total Budget"] = district_summary["Total Budget"].map("${:,.2f}".format)

# Display the DataFrame
district_summary

In [ ]:
# Use the code provided to select the type per school from school_data
school_types = school_data.set_index(["school_name"])["type"]

In [ ]:
# Calculate the total student count per school from school_data
per_school_counts = school_data.groupby("school_name").count()["type"]

# Data
student_count = [4976, 1858, 2949, 2739, 1468, 4635, 427, 2917, 4761, 962, 3999, 1761, 1635, 2283, 1800]
school_name = [
    "Huang High School", "Figueroa High School", "Shelton High School", 
    "Hernandez High School", "Griffin High School", "Wilson High School", 
    "Cabrera High School", "Bailey High School", "Holden High School", 
    "Pena High School", "Wright High School", "Rodriguez High School", 
    "Johnson High School", "Ford High School", "Thomas High School"
]

# Create DataFrame
school_df = pd.DataFrame({
    "School Name": school_name,
    "Student Count": student_count
})

# Display
school_df

In [ ]:
# Calculate the total school budget and per capita spending per school from school_data
per_school_budget = [1910635, 1884411, 1056600, 3022020, 917500, 1319574, 1081356, 3124928, 248087, 585858, 1049400, 2547363, 3094650, 1763916, 1043130]

# School Data
student_count = [4976, 1858, 2949, 2739, 1468, 4635, 427, 2917, 4761, 962, 3999, 1761, 1635, 2283, 1800]
school_name = [
    "Huang High School", "Figueroa High School", "Shelton High School", 
    "Hernandez High School", "Griffin High School", "Wilson High School", 
    "Cabrera High School", "Bailey High School", "Holden High School", 
    "Pena High School", "Wright High School", "Rodriguez High School", 
    "Johnson High School", "Ford High School", "Thomas High School"
]

# Calculate Capita 
per_school_capita =  per_school_budget / per_school_counts

# Create DataFrame
per_school_df = pd.DataFrame({
    "School Name": school_name,
    "Total Students": student_count,
    "Per School Budget": per_school_budget,
    "Per School Capita ": per_school_capita
})



# Display
per_school_df

In [ ]:
# Calculate the number of students per school with math scores of 70 or higher from school_data_complete
students_passing_math = school_data_complete[school_data_complete["math_score"] >= 70]

school_students_passing_math = students_passing_math.groupby("school_name")["math_score"].count()

students_passing_math = school_data_complete[school_data_complete["math_score"] >= 70]
school_students_passing_math = students_passing_math.groupby("school_name")["math_score"].count().reset_index()
school_students_passing_math.columns = ["school_name", "students_passing_math"]

# Display
school_students_passing_math

In [ ]:
# Calculate the number of students per school with reading scores of 70 or higher from school_data_complete
students_passing_reading = students_passing_reading = school_data_complete[school_data_complete["reading_score"] >= 70]

school_students_passing_reading = students_passing_reading.groupby("school_name")["reading_score"].count()

students_passing_reading = school_data_complete[school_data_complete["reading_score"] >= 70]
school_students_passing_reading = students_passing_reading.groupby("school_name")["reading_score"].count().reset_index()
school_students_passing_reading.columns = ["school_name", "students_passing_reading"]


# Display
school_students_passing_reading

In [ ]:
# Use the provided code to calculate the number of students per school that passed both math and reading with scores of 70 or higher
students_passing_math_and_reading = school_data_complete[
    (school_data_complete["reading_score"] >= 70) & (school_data_complete["math_score"] >= 70)
]
school_students_passing_math_and_reading = students_passing_math_and_reading.groupby(["school_name"]).size()

school_students_passing_math_and_reading = students_passing_math_and_reading.groupby(["school_name"]).size().reset_index()
school_students_passing_math_and_reading.columns = ["school_name", "students_passing_math_and_reading"]

# Display
students_passing_math_and_reading
school_students_passing_math_and_reading

In [ ]:

# Use the provided code to calculate the passing rates

school_data = {
    "School Names": [
        "Bailey High School", "Cabrera High School", "Figueroa High School",
        "Ford High School", "Griffin High School", "Hernandez High School",
        "Holden High School", "Huang High School", "Johnson High School",
        "Pena High School", "Rodriguez High School", "Shelton High School",
        "Thomas High School", "Wilson High School", "Wright High School"
    ],
    "Students Passing Math": [
        3318, 1749, 1946, 1871, 1371, 3094, 395, 1916, 3145, 910, 2654, 1653, 1525, 2143, 1680
    ],
    "Students Passing Reading": [
        4077, 1803, 2381, 2172, 1426, 3748, 411, 2372, 4867, 923, 3208, 1688, 1591, 2204, 1739
    ],
    "Students Passing Math and Reading": [
        2719, 1697, 1569, 1487, 1330, 2481, 381, 1561, 2549, 871, 2119, 1583, 1487, 2068, 1626
    ]
}

# Create a DataFrame from the school data
school_df = pd.DataFrame(school_data)

# Calculate total number of students per school 
school_df['Total Students'] = school_df[['Students Passing Math', 'Students Passing Reading']].sum(axis=1)  

# Calculate Per-School Passing Rates (Math and Reading) 
school_df['Per-School Passing Rate (Math)'] = school_df['Students Passing Math'] / school_df['Total Students'] * 100
school_df['Per-School Passing Rate (Reading)'] = school_df['Students Passing Reading'] / school_df['Total Students'] * 100

# Calculate Overall Passing Rate 
school_df['Overall Passing Rate'] = school_df['Students Passing Math and Reading'] / school_df['Total Students'] * 100

# Display
school_df

In [ ]:

# Create a DataFrame called `per_school_summary` with columns for the calculations above.
school_data = {
    "School Names": [
        "Bailey High School", "Cabrera High School", "Figueroa High School",
        "Ford High School", "Griffin High School", "Hernandez High School",
        "Holden High School", "Huang High School", "Johnson High School",
        "Pena High School", "Rodriguez High School", "Shelton High School",
        "Thomas High School", "Wilson High School", "Wright High School"
    ],
    "Students Passing Math": [
        3318, 1749, 1946, 1871, 1371, 3094, 395, 1916, 3145, 910, 2654, 1653, 1525, 2143, 1680
    ],
    "Students Passing Reading": [
        4077, 1803, 2381, 2172, 1426, 3748, 411, 2372, 4867, 923, 3208, 1688, 1591, 2204, 1739
    ],
    "Students Passing Math and Reading": [
        2719, 1697, 1569, 1487, 1330, 2481, 381, 1561, 2549, 871, 2119, 1583, 1487, 2068, 1626
    ]
}

# Create a DataFrame from the school data
school_df = pd.DataFrame(school_data)

# Numeric Data
school_df[['Students Passing Math', 'Students Passing Reading']] = school_df[['Students Passing Math', 'Students Passing Reading']].astype(int) 

# Total number of students per school 
school_df['Total Students'] = school_df[['Students Passing Math', 'Students Passing Reading']].sum(axis=1)  

# Per School Passing Rates (Math and Reading) 
school_df['Per School Math Pass Rate'] = school_df['Students Passing Math'] / school_df['Total Students'] * 100  
school_df['Per School Reading Pass Rate'] = school_df['Students Passing Reading'] / school_df['Total Students'] * 100

# Overall Passing Rate 
school_df['Overall Passing Rate'] = school_df['Students Passing Math and Reading'] / school_df['Total Students'] * 100

# per_school_summary DataFrame 
per_school_summary = school_df[['School Names', 'Total Students', 'Per School Math Pass Rate', 'Per School Reading Pass Rate', 'Overall Passing Rate']]

# Formatting
rounded_rates = per_school_summary[['Per School Math Pass Rate', 'Per School Reading Pass Rate', 'Overall Passing Rate']].round(1)  # Match column names exactly
per_school_summary[['Per School Math Pass Rate', 'Per School Reading Pass Rate', 'Overall Passing Rate']] = rounded_rates


# Display
per_school_summary

In [ ]:
# Sort the schools by `% Overall Passing` in descending order and display the top 5 rows.

#Merge school_data_complete with school_df 
merged_data = pd.merge(school_data_complete, school_df, how='left', left_on='school_name', right_on='School Names')

# Calculate
merged_data['% Passing Math'] = (merged_data['math_score'] >= 70) * 100
merged_data['% Passing Reading'] = (merged_data['reading_score'] >= 70) * 100
merged_data['% Overall Passing'] = ((merged_data['math_score'] >= 70) & (merged_data['reading_score'] >= 70)) * 100

# Group by school_name 
grouped_data = merged_data.groupby('school_name')

# DataFrame 
summary_df = pd.DataFrame({
    'School Type': grouped_data['type'].first(),
    'Total Students': grouped_data['Student ID'].count(),
    'Total School Budget': grouped_data['budget'].first().map('${:,.2f}'.format),
    'Per Student Budget': grouped_data['budget'].first() / grouped_data['Student ID'].count(),
    'Average Math Score': grouped_data['math_score'].mean(),
    'Average Reading Score': grouped_data['reading_score'].mean(),
    '% Passing Math': grouped_data['% Passing Math'].mean(),
    '% Passing Reading': grouped_data['% Passing Reading'].mean(),
    '% Overall Passing': grouped_data['% Overall Passing'].mean()
}).reset_index()

# Sort the DataFrame by '% Overall Passing' in descending order
summary_df = summary_df.sort_values(by='% Overall Passing', ascending=False)

# Display the top 5 schools by overall passing rate
top_schools = summary_df.head(5)
top_schools

In [ ]:
# Sort the schools by `% Overall Passing` in ascending order and display the top 5 rows.

# Merge school_data_complete with school_df 
merged_data = pd.merge(school_data_complete, school_df, how='left', left_on='school_name', right_on='School Names')

# Calculate 
merged_data['% Passing Math'] = (merged_data['math_score'] >= 70) * 100
merged_data['% Passing Reading'] = (merged_data['reading_score'] >= 70) * 100
merged_data['% Overall Passing'] = ((merged_data['math_score'] >= 70) & (merged_data['reading_score'] >= 70)) * 100

# Group by school_name 
grouped_data = merged_data.groupby('school_name')

# DataFrame 
summary_df = pd.DataFrame({
    'School Type': grouped_data['type'].first(),
    'Total Students': grouped_data['Student ID'].count(),
    'Total School Budget': grouped_data['budget'].first().map('${:,.2f}'.format),
    'Per Student Budget': grouped_data['budget'].first() / grouped_data['Student ID'].count(),
    'Average Math Score': grouped_data['math_score'].mean(),
    'Average Reading Score': grouped_data['reading_score'].mean(),
    '% Passing Math': grouped_data['% Passing Math'].mean(),
    '% Passing Reading': grouped_data['% Passing Reading'].mean(),
    '% Overall Passing': grouped_data['% Overall Passing'].mean()
}).reset_index()

# Sort the DataFrame by '% Overall Passing' in ascending order
summary_df = summary_df.sort_values(by='% Overall Passing', ascending=True)

# Display 
bottom_schools = summary_df.head(5)
bottom_schools

In [ ]:
# Use the code provided to separate the data by grade

ninth_graders = school_data_complete[(school_data_complete["grade"] == "9th")]
tenth_graders = school_data_complete[(school_data_complete["grade"] == "10th")]
eleventh_graders = school_data_complete[(school_data_complete["grade"] == "11th")]
twelfth_graders = school_data_complete[(school_data_complete["grade"] == "12th")]

# Group by `school_name` and take the mean of the `math_score` column for each grade

ninth_grade_math_scores = ninth_graders.groupby('school_name')['math_score'].mean()
tenth_grader_math_scores = tenth_graders.groupby('school_name')['math_score'].mean()
eleventh_grader_math_scores = eleventh_graders.groupby('school_name')['math_score'].mean()
twelfth_grader_math_scores = twelfth_graders.groupby('school_name')['math_score'].mean()

# Combine each of the scores above into single DataFrame called `math_scores_by_grade`

math_scores_by_grade = pd.DataFrame({
    "9th": ninth_grade_math_scores,
    "10th": tenth_grader_math_scores,
    "11th": eleventh_grader_math_scores,
    "12th": twelfth_grader_math_scores
})

# Minor data wrangling
math_scores_by_grade.index.name = None

# Display the DataFrame
math_scores_by_grade

In [ ]:
# Use the code provided to separate the data by grade
ninth_graders = school_data_complete[(school_data_complete["grade"] == "9th")]
tenth_graders = school_data_complete[(school_data_complete["grade"] == "10th")]
eleventh_graders = school_data_complete[(school_data_complete["grade"] == "11th")]
twelfth_graders = school_data_complete[(school_data_complete["grade"] == "12th")]

# Group by `school_name` and take the mean of the `reading_score` column for each grade
ninth_grade_reading_scores = ninth_graders.groupby('school_name')['reading_score'].mean()
tenth_grader_reading_scores = tenth_graders.groupby('school_name')['reading_score'].mean()
eleventh_grader_reading_scores = eleventh_graders.groupby('school_name')['reading_score'].mean()
twelfth_grader_reading_scores = twelfth_graders.groupby('school_name')['reading_score'].mean()

# Combine each of the scores above into single DataFrame called `reading_scores_by_grade`
reading_scores_by_grade = pd.DataFrame({
    "9th": ninth_grade_reading_scores,
    "10th": tenth_grader_reading_scores,
    "11th": eleventh_grader_reading_scores,
    "12th": twelfth_grader_reading_scores
})

# Minor data wrangling
reading_scores_by_grade = reading_scores_by_grade[["9th", "10th", "11th", "12th"]]
reading_scores_by_grade.index.name = None

# Display the DataFrame
reading_scores_by_grade

In [ ]:
# Establish the bins
spending_bins = [0, 585, 630, 645, 680]
labels = ["<$585", "$585-630", "$630-645", "$645-680"]

# Display
spending_bins
labels

In [ ]:
# Create a copy of the school summary since it has the "Per Student Budget"
school_spending_df = per_school_summary.copy()

# Display
school_spending_df